#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
usr/lib/openfoam/openfoam2306/wmake/scripts/AllwmakeParseArguments

libSrc/Allwmake $targetType $*
( cd appSrc && wmake )
tools/Allwmake $targetType $*

#------------------------------------------------------------------------------
